import {
  User,
  UserRole,
  Student,
  PickupZone,
  PickupZoneId,
  PickupRequest,
  PickupStatus,
  TransportationType,
  NotificationItem,
} from '../types';

export const INITIAL_USERS: User[] = [];

export const INITIAL_ZONES: PickupZone[] = [
  {
    id: PickupZoneId.ZONE_A,
    name: 'Khu A',
    grades: '6A1, 6A2',
    assignedClasses: ['6A1', '6A2'],
    description: 'Khu vực Cổng Chính (Làn số 1)',
    color: '#10B981', // green
    currentVehicles: 8,
    maxCapacity: 25,
    waitingPeople: 5,
  },
  {
    id: PickupZoneId.ZONE_B,
    name: 'Khu B',
    grades: '7A1, 7A2',
    assignedClasses: ['7A1', '7A2'],
    description: 'Khu vực Sân Trung Tâm (Làn số 2)',
    color: '#2563EB', // blue
    currentVehicles: 15,
    maxCapacity: 30,
    waitingPeople: 12,
  },
  {
    id: PickupZoneId.ZONE_C,
    name: 'Khu C',
    grades: '8A1, 8A2',
    assignedClasses: ['8A1', '8A2'],
    description: 'Khu vực Cổng Phía Tây (Làn số 3)',
    color: '#EAB308', // yellow
    currentVehicles: 6,
    maxCapacity: 20,
    waitingPeople: 4,
  },
  {
    id: PickupZoneId.ZONE_D,
    name: 'Khu D',
    grades: '9A1, 9A2',
    assignedClasses: ['9A1', '9A2'],
    description: 'Khu vực Hành Lang Phía Đông (Làn số 4)',
    color: '#F97316', // orange
    currentVehicles: 4,
    maxCapacity: 20,
    waitingPeople: 2,
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'student-1',
    name: 'Nguyễn Minh Bảo',
    classId: 'class-7a1',
    className: '7A1',
    grade: 7,
    pickupZoneId: PickupZoneId.ZONE_B,
    parentId: 'parent-1',
    parentName: 'Nguyễn Văn An',
    parentPhone: '0912 345 678',
  },
  {
    id: 'student-2',
    name: 'Nguyễn Minh An',
    classId: 'class-5b2',
    className: '5B2',
    grade: 5,
    pickupZoneId: PickupZoneId.ZONE_A,
    parentId: 'parent-1',
    parentName: 'Nguyễn Văn An',
    parentPhone: '0912 345 678',
  },
  {
    id: 'student-3',
    name: 'Trần Minh Anh',
    classId: 'class-7a1',
    className: '7A1',
    grade: 7,
    pickupZoneId: PickupZoneId.ZONE_B,
    parentId: 'parent-2',
    parentName: 'Trần Quốc Bảo',
    parentPhone: '0934 111 222',
  },
  {
    id: 'student-4',
    name: 'Lê Hoàng Nam',
    classId: 'class-7a1',
    className: '7A1',
    grade: 7,
    pickupZoneId: PickupZoneId.ZONE_B,
    parentId: 'parent-3',
    parentName: 'Lê Văn Tuấn',
    parentPhone: '0945 222 333',
  },
  {
    id: 'student-5',
    name: 'Phạm Gia Hân',
    classId: 'class-7a1',
    className: '7A1',
    grade: 7,
    pickupZoneId: PickupZoneId.ZONE_B,
    parentId: 'parent-4',
    parentName: 'Phạm Hồng Nhung',
    parentPhone: '0967 888 999',
  },
  {
    id: 'student-6',
    name: 'Đặng Quốc Huy',
    classId: 'class-7a1',
    className: '7A1',
    grade: 7,
    pickupZoneId: PickupZoneId.ZONE_B,
    parentId: 'parent-5',
    parentName: 'Đặng Văn Tiến',
    parentPhone: '0918 333 444',
  },
  {
    id: 'student-7',
    name: 'Vũ Mai Chi',
    classId: 'class-7a1',
    className: '7A1',
    grade: 7,
    pickupZoneId: PickupZoneId.ZONE_B,
    parentId: 'parent-6',
    parentName: 'Vũ Thị Hòa',
    parentPhone: '0922 444 555',
  },
  {
    id: 'student-8',
    name: 'Hoàng Tuấn Kiệt',
    classId: 'class-7a1',
    className: '7A1',
    grade: 7,
    pickupZoneId: PickupZoneId.ZONE_B,
    parentId: 'parent-7',
    parentName: 'Hoàng Anh Dũng',
    parentPhone: '0981 555 666',
  },
];

export const INITIAL_REQUESTS: PickupRequest[] = [
  {
    id: 'req-21',
    queueNumber: 21,
    studentId: 'student-7',
    studentName: 'Vũ Mai Chi',
    classId: 'class-7a1',
    className: '7A1',
    parentId: 'parent-6',
    parentName: 'Vũ Thị Hòa',
    parentPhone: '0922 444 555',
    pickupZoneId: PickupZoneId.ZONE_B,
    transportationType: TransportationType.MOTORBIKE,
    status: PickupStatus.PICKED_UP,
    createdAt: '16:05',
    preparedAt: '16:08',
    readyAt: '16:11',
    pickedUpAt: '16:14',
  },
  {
    id: 'req-22',
    queueNumber: 22,
    studentId: 'student-8',
    studentName: 'Hoàng Tuấn Kiệt',
    classId: 'class-7a1',
    className: '7A1',
    parentId: 'parent-7',
    parentName: 'Hoàng Anh Dũng',
    parentPhone: '0981 555 666',
    pickupZoneId: PickupZoneId.ZONE_B,
    transportationType: TransportationType.CAR,
    status: PickupStatus.PICKED_UP,
    createdAt: '16:10',
    preparedAt: '16:12',
    readyAt: '16:15',
    pickedUpAt: '16:17',
  },
  {
    id: 'req-23',
    queueNumber: 23,
    studentId: 'student-6',
    studentName: 'Đặng Quốc Huy',
    classId: 'class-7a1',
    className: '7A1',
    parentId: 'parent-5',
    parentName: 'Đặng Văn Tiến',
    parentPhone: '0918 333 444',
    pickupZoneId: PickupZoneId.ZONE_B,
    transportationType: TransportationType.CAR,
    status: PickupStatus.READY,
    createdAt: '16:15',
    preparedAt: '16:18',
    readyAt: '16:20',
  },
  {
    id: 'req-25',
    queueNumber: 25,
    studentId: 'student-3',
    studentName: 'Trần Minh Anh',
    classId: 'class-7a1',
    className: '7A1',
    parentId: 'parent-2',
    parentName: 'Trần Quốc Bảo',
    parentPhone: '0934 111 222',
    pickupZoneId: PickupZoneId.ZONE_B,
    transportationType: TransportationType.MOTORBIKE,
    status: PickupStatus.PREPARING,
    createdAt: '16:18',
    preparedAt: '16:21',
  },
  {
    id: 'req-26',
    queueNumber: 26,
    studentId: 'student-4',
    studentName: 'Lê Hoàng Nam',
    classId: 'class-7a1',
    className: '7A1',
    parentId: 'parent-3',
    parentName: 'Lê Văn Tuấn',
    parentPhone: '0945 222 333',
    pickupZoneId: PickupZoneId.ZONE_B,
    transportationType: TransportationType.WALK,
    status: PickupStatus.REQUESTED,
    createdAt: '16:20',
  },
  {
    id: 'req-27',
    queueNumber: 27,
    studentId: 'student-5',
    studentName: 'Phạm Gia Hân',
    classId: 'class-7a1',
    className: '7A1',
    parentId: 'parent-4',
    parentName: 'Phạm Hồng Nhung',
    parentPhone: '0967 888 999',
    pickupZoneId: PickupZoneId.ZONE_B,
    transportationType: TransportationType.CAR,
    status: PickupStatus.REQUESTED,
    createdAt: '16:21',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipientRole: UserRole.TEACHER,
    title: 'Phụ huynh đang đến',
    message: 'Phụ huynh của Phạm Gia Hân (7A1) đã báo đang đến Khu B bằng Ô tô.',
    timestamp: '16:21',
    isRead: false,
    type: 'ALERT',
    studentName: 'Phạm Gia Hân',
  },
  {
    id: 'notif-2',
    recipientRole: UserRole.TEACHER,
    title: 'Phụ huynh đang đến',
    message: 'Phụ huynh của Lê Hoàng Nam (7A1) đã đến Khu B (Đi bộ).',
    timestamp: '16:20',
    isRead: true,
    type: 'INFO',
    studentName: 'Lê Hoàng Nam',
  },
  {
    id: 'notif-3',
    recipientRole: UserRole.PARENT,
    recipientId: 'parent-1',
    title: 'Chào mừng đến SchoolPick',
    message: 'Hệ thống đón học sinh trường THCS Ban Mai đã bắt đầu giờ tan học.',
    timestamp: '16:00',
    isRead: true,
    type: 'INFO',
  },
];
